#! /bin/sh

# ------------------------------
# Startup
# ------------------------------

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill --no-fehbg --randomize ~/images/wallpapers
picom &

# ------------------------------
# Monitors
# ------------------------------

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

# ------------------------------
# Global configs
# ------------------------------

bspc config border_width         5
bspc config window_gap           20
spc config split_ratio          0.50

# ------------------------------
# Colors
# ------------------------------

bspc config focused_border_color "#E84F4F"
bspc config active_border_color "#D23D3D"

# ------------------------------
# Rules
# ------------------------------

bspc rule -a Zathura state=tiled
